# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retaurants',
            new_name='Restaurant',
        ),
    ]
